name = "codefromanywhere_lilissues_main"
compatibility_date = "2024-11-10"
assets = { directory = "./" }
main = "index.ts"

[vars]
GITHUB_PAT = ""
ANTHROPIC_API_KEY = ""
STRIPE_SECRET_KEY = ""
STRIPE_WEBHOOK_SECRET = ""
